### ISSUE TITLE
Fix settings saving

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/OctoPrint-Webhooks#1]
As mentioned in https://github.com/2blane/OctoPrint-Webhooks/issues/19 there is something wonky about how the plugin manages settings. This is going to track fixing that

_Possibly also related to https://github.com/2blane/OctoPrint-Webhooks/issues/26 - though this one seems weird as I don't think it's really possible to delete the settings for other plugins (plus there's no repro steps)_

**Comment by derekantrican** [comment]
Here's a great example:

![Vdxliyx4Yp](https://user-images.githubusercontent.com/1558019/216521713-60315d8f-3586-4e0d-834d-8a60fd7fb819.gif)

Note:

1. The webhook "enabled" is unchecked - _this successfully gets saved to the settings_
2. The webhook "enabled" is checked - _this does NOT get saved_
3. Extra text is added to one of the webhook event messages - _this also does NOT get saved_
4. On a refresh of the page (and a reload from the saved settings) we can see that those last two changes were never saved.

**Comment by derekantrican** [comment]
Also, the note in the "Testing" section (emphasis added):

> Send test events to your server to make sure everything is configured correctly.
**Note: if a popup appears telling you "Settings update detected", click outside the popup to dismiss it. Don't select one of the options.**

That seems weird and possibly because of the problems with saving settings.

**Comment by derekantrican** [comment]
For transparency, here's the forum thread where I've been working with jneilliii: https://community.octoprint.org/t/settingsupdated-event-only-fires-once-per-session/38986/11

**Comment by matteosandrin** [comment]
Just wanted to chime in to report that I am also seeing some issues in saving settings. For example I had initially saved the "headers" section as empty, which successfully saved. After I filled in the headers field and saved settings again, the test alert would not fire, saying the headers were still empty. After I went into the `config.yaml` file and manually filled in the headers field, the alert worked perfectly.

Therefore, I believe there is an issue with how the settings are being saved.

**Comment by derekantrican** [comment]
Seems that saving settings for a webhook works once after the window is loaded, but then the binding (or observing) is lost as any further changes don't get reflected. _However_, it seems that if the selected webhook is changed, then changed back (forcing the `selectHook` function, I think) then the bindings are working again (see screen recording below).

_In the below screen recording, the plugin settings in config.yaml are on the left. Note the `webhook_enabled` setting along with the "Disabled" UI badget next to the selected webhook_

![Code_l2PzNcKUlD](https://github.com/derekantrican/OctoPrint-Webhooks/assets/1558019/605b24d7-e995-4d67-9118-4ac5025c6309)

**Comment by derekantrican** [comment]
Ok, I have hijacked the "Send Test Webhook" button to output data about the current webhook:

```js
console.log("SELECTED INDEX:", self.selectedIndex());
console.log("SELECTED HOOK:", self.selectedHook());
console.log("SELECTED HOOK ENABLED?", self.selectedHook().webhook_enabled());
console.log("SELECTED HOOK (settings) ENABLED?", self.settings.settings.plugins.webhooks.hooks()[self.selectedIndex()].webhook_enabled());
```

What I have found is that the `selectedHook` observable is _still working_, but it has somehow become disconnected from the corresponding `self.settings.settings.plugins.webhooks.hooks()[self.selectedIndex()]` object in the actual settings. Changing the selected hook back and forth (as mentioned above) clearly fixes this because that reassigns `self.selectedHook(self.settings.settings.plugins.webhooks.hooks()[index])`.

![brave_0IM28JCu4c](https://github.com/derekantrican/OctoPrint-Webhooks/assets/1558019/ab48de8c-d8d0-4d63-aab2-630d16ddc1e6)

**Comment by derekantrican** [comment]
> _It's as if, when the settings are saved, new observables are created. So the `selectedHook` is no longer the same observable object after the settings are saved_

Pretty sure this is indeed what's happening. Seems to be resolved with https://github.com/derekantrican/OctoPrint-Webhooks/commit/c75f33a1e380a330f7824f17589c28937e196e49
