### ISSUE TITLE
Request for option to disable https certificate verification

### ISSUE THREAD

**Issue by sebeksd** [derekantrican/OctoPrint-Webhooks#10]
Hello.
I'm using Octorpint Webhooks to send notification through self hosted Ntfy server. My server is using LetsEncrypt certificates and python don't like them (curl too) so I need to disable certificate verification.
In different application there is often a checkbox to disable cert verification.

Already check myself that setting "verify=False" (hardcoded locally in Webhooks sourcecode) is working. Please add checkbox to disable certificate verification per webhook.

**Comment by derekantrican** [comment]
I just added this via https://github.com/derekantrican/OctoPrint-Webhooks/commit/40820674dd92f0e801e815b88eb564eedb57d3ff

Can you test it out for me?

1. Go to OctoPrint > Settings > Plugin Manager > "Get More" button in the top right
2. In the "From URL" box, put this: https://github.com/derekantrican/OctoPrint-Webhooks/archive/VerifySsl.zip
3. Click "Install"
4. If you are not prompted to restart octoprint, go ahead and do so

The new setting is a checkbox under the "Advanced" options:
![image](https://github.com/derekantrican/OctoPrint-Webhooks/assets/1558019/23dfdd8e-409f-4d52-8e0b-0274d986e2b6)

**Comment by sebeksd** [comment]
Hi, It is working perfectly :) Thank you.

How I tested it:
- uninstalled Webhooks I already had and manually modified (to be sure it doesn't affect tests)
- installed original version from Plugin manager and tested if it fails (and it did fail)
- installed version from URL and tested with checkbox checked (failed as it should) and with checkbox unchecked (worked as it should :))
