### ISSUE TITLE
Invalid API response (Discord)

### ISSUE THREAD

**Issue by headcase0570** [derekantrican/OctoPrint-Webhooks#3]
Thought I'd try setting up a Discord webhook. 
I keep getting this error regardless of whatever settings I try.

`Webhooks
Invalid API Response: {"message": "Cannot send an empty message", "code": 50006}`

I get these messages when I'm trying to both send a test message (any) or starting a print.
Update: I get this error even when having removed all webhook URLS.

**Comment by derekantrican** [comment]
> Update: I get this error even when having removed all webhook URLS.

Please update to the latest plugin version 3.2.0 that fixes settings saving and try again.

If you're still facing this issue, please provide some more information (screenshots - feel free to edit sensitive data like your webhook url, what steps you performed in the plugin, etc)

**Comment by derekantrican** [comment]
_Closing this issue as the settings saving is likely fixed. However, if you are still facing the "Invalid API Response" error in the latest version, please reopen this issue._
