### ISSUE TITLE
Resume Webhook

### ISSUE THREAD

**Issue by r34220** [derekantrican/OctoPrint-Webhooks#4]
Can you add a Resume Webook? Have a need know when a print has been resumed.

**Comment by derekantrican** [comment]
Sounds like this could be solved by #2 once I implement that as the custom event could be set to `PrintResumed` per the https://docs.octoprint.org/en/master/events/index.html#available-events

**Comment by derekantrican** [comment]
Please update to version 4.0.0 of the plugin - this should now be available
