### ISSUE TITLE
Event "cooldown" to limit multiple webhook calls per event

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/OctoPrint-Webhooks#5]
Some events get triggered many times for one "real event". https://github.com/2blane/OctoPrint-Webhooks/issues/15 reports that for "user action needed" and "print started". I've also seen this when developing #2 with some events like "UserLoggedIn

Looks like there was a PR to attempt to fix some of this by just hardcoding a 60 second "cooldown": https://github.com/2blane/OctoPrint-Webhooks/pull/37

At a minimum, I'd like a cooldown time user setting, but I may want to look into bypassing the cooldown if the payload has changed (eg the PrintStarted event includes the file's name - if the PrintStarted event is fired again within a cooldown period of 60 seconds but with a different file name, then we should bypass the cooldown).

**Comment by Outshynd** [comment]
I definitely prefer your idea over my hard-coded implementation. I'm no python dev and the event spam was driving me crazy. I look forward to the future of this project. I ended up switching to OctoRant for similar functionality, though I miss the simplicity of this plugin.

**Comment by derekantrican** [comment]
FYI - started working on this https://github.com/derekantrican/OctoPrint-Webhooks/tree/EventCooldown
